= UD Library for Arduino =

The UD library allows for reading from and writing to extern SPIflash.

This library is modified from Arduino's SD library,you can visit their at
http://www.arduino.cc/en/Reference/SD
Copyright (C) 2009 by William Greiman
Copyright (c) 2010 SparkFun Electronics
Copyright (c) 2010 DFRobot Co.Ltd
== License ==
GNU General Public License V3
          (Because sdfatlib is licensed with this.)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
